language: python
python:
  - "3.5"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-4.0.5-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda env create -f environment.yml -n test-environment
  - source activate test-environment
script: python -m pytest -vv ./
